/*
 * DlgLogin.java
 *
 * Created on 5 de diciembre de 2004, 09:12 PM
 */

/**
 *
 * @author  Administrador
 */
public class DlgLogin extends javax.swing.JDialog 
{
    ClsGestorEscBaile objGestor;
    /** Creates new form DlgLogin */
    public DlgLogin(java.awt.Frame parent, ClsGestorEscBaile unGestor )
    {
        super(parent, true);
        initComponents();
        objGestor = unGestor;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jBtnSalir = new javax.swing.JButton();
        jBtnProcede = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jTxtPwd = new javax.swing.JTextField();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Escuela de Baile: Sistema de Administraci\u00f3n e Cursos.");
        setModal(true);
        setResizable(false);
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, 70, -1));

        jBtnProcede.setText("Procede");
        jBtnProcede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProcedeActionPerformed(evt);
            }
        });

        getContentPane().add(jBtnProcede, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jLabel1.setText("Usuario:");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 50, 20));

        jLabel2.setText("Contrase\u00f1a:");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 70, 20));

        jTxtUsuario.setText("rafa");
        getContentPane().add(jTxtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 120, -1));

        jTxtPwd.setText("rafa");
        getContentPane().add(jTxtPwd, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 120, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-401)/2, (screenSize.height-174)/2, 401, 174);
    }//GEN-END:initComponents

    private void jBtnProcedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProcedeActionPerformed
        // TODO add your handling code here:
      objGestor.conectaBD( jTxtUsuario.getText(), jTxtPwd.getText());
      dispose();
        
    }//GEN-LAST:event_jBtnProcedeActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
      ClsGestorEscBaile gestor = new ClsGestorEscBaile();
      DlgLogin dlgLogin = new DlgLogin(new javax.swing.JFrame(), gestor );
      dlgLogin.show();
       if( gestor.conectado())    
        System.out.println("Se ha conectado a la base de datos" );
       else
        System.out.println("No hubo conexión" );  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnProcede;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTxtPwd;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
    
}
