/*
 * FrmAlumnos.java
 *
 * Created on 6 de diciembre de 2004, 08:25 PM
 */

/**
 *
 * @author  Administrador
 */
public class FrmAlumnos extends javax.swing.JFrame
{
    ClsGestorEscBaile objGestor;
    /** Creates new form FrmAlumnos */
    public FrmAlumnos (ClsGestorEscBaile unGestor )
    {
        objGestor = unGestor;
        initComponents ();
    }
  // --------------------------------------------------------------------------    
    private MiModelo obtenModelo()
    {
        java.sql.ResultSet r;
        r = objGestor.obtenAlumnos();
        //System.out.println(con.impRS(r));
        MiModelo mm = new MiModelo( r );
        try
        {
            r.close();
        }
        catch( Exception e )
        {
            e.printStackTrace();
        }
        return mm;
    }
    
    private ModeloLista obtenModeloLista(String strTV,String strCampo)
    {
        java.sql.ResultSet r = objGestor.obtenCampoParaLista (strTV, strCampo);
        //System.out.println(con.impRS(r));
        ModeloLista ml = new ModeloLista( r );
        try
        {
            r.close();
        }
        catch( Exception e )
        {
            e.printStackTrace();
        }
    
        return ml;        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jBtnAltaAlumno = new javax.swing.JButton();
        jBtnEditarAlumno = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setTitle("Mantenimiento a Datos de Alumnos.");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jTable1.setModel(obtenModelo());
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 360, 180));

        jBtnAltaAlumno.setText("Alta de Alumno");
        jBtnAltaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAltaAlumnoActionPerformed(evt);
            }
        });

        getContentPane().add(jBtnAltaAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jBtnEditarAlumno.setText("Editar Registro");
        jBtnEditarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarAlumnoActionPerformed(evt);
            }
        });

        getContentPane().add(jBtnEditarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jBtnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSalirMouseClicked(evt);
            }
        });

        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 110, -1));

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-410)/2, (screenSize.height-322)/2, 410, 322);
    }//GEN-END:initComponents

    private void jBtnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSalirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSalirMouseClicked

    private void jBtnEditarAlumnoActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnEditarAlumnoActionPerformed
    {//GEN-HEADEREND:event_jBtnEditarAlumnoActionPerformed
        // TODO add your handling code here:
       new DlgMensajes(new javax.swing.JFrame(),"Edición de alumno","Implantar la edición de los datos del alumno").show();
    }//GEN-LAST:event_jBtnEditarAlumnoActionPerformed

    private void jBtnSalirActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnSalirActionPerformed
    {//GEN-HEADEREND:event_jBtnSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnAltaAlumnoActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAltaAlumnoActionPerformed
    {//GEN-HEADEREND:event_jBtnAltaAlumnoActionPerformed
        // TODO add your handling code here:
        new DlgMensajes(new javax.swing.JFrame(),"Alta de alumno","Implantar el alta del alumno").show();
    }//GEN-LAST:event_jBtnAltaAlumnoActionPerformed
    
    /** Exit the Application */
    private void exitForm (java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
    {
       dispose();
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        new FrmAlumnos (null).show ();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAltaAlumno;
    private javax.swing.JButton jBtnEditarAlumno;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    
}
