/*
 * FrmMenuPrincipal.java
 *
 * Created on 6 de diciembre de 2004, 04:27 PM
 */

/**
 *
 * @author  Administrador
 */
public class FrmMenuPrincipal extends javax.swing.JFrame
{
    ClsGestorEscBaile objGestor;
    /** Creates new form FrmMenuPrincipal */
    public FrmMenuPrincipal (ClsGestorEscBaile unGestor )
    {
        objGestor = unGestor;
        initComponents ();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents() {//GEN-BEGIN:initComponents
        menuBar = new javax.swing.JMenuBar();
        menuBasicos = new javax.swing.JMenu();
        opcAlumnos = new javax.swing.JMenuItem();
        opcProfesores = new javax.swing.JMenuItem();
        opcGrupos = new javax.swing.JMenuItem();
        opcBailes = new javax.swing.JMenuItem();
        opcNiveles = new javax.swing.JMenuItem();
        menuInscripciones = new javax.swing.JMenu();
        menuAyuda = new javax.swing.JMenu();
        opcAyudaUso = new javax.swing.JMenuItem();
        opcAcercaDe = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JMenu();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Informaci\u00f3n de la Escuela de Baile. Menu Principal.");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cerrarConexion(evt);
            }
        });

        menuBasicos.setText("B\u00e1sicos");
        opcAlumnos.setText("Alumnos");
        opcAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAlumnosActionPerformed(evt);
            }
        });

        menuBasicos.add(opcAlumnos);

        opcProfesores.setText("Profesores");
        opcProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcProfesoresActionPerformed(evt);
            }
        });

        menuBasicos.add(opcProfesores);

        opcGrupos.setText("Grupos");
        opcGrupos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcGruposActionPerformed(evt);
            }
        });

        menuBasicos.add(opcGrupos);

        opcBailes.setText("Bailes");
        opcBailes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcBailesActionPerformed(evt);
            }
        });

        menuBasicos.add(opcBailes);

        opcNiveles.setText("Niveles");
        opcNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcNivelesActionPerformed(evt);
            }
        });

        menuBasicos.add(opcNiveles);

        menuBar.add(menuBasicos);

        menuInscripciones.setText("Inscripciones");
        menuInscripciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuInscripciones_onMouseClicked(evt);
            }
        });

        menuBar.add(menuInscripciones);

        menuAyuda.setText("Ayuda");
        opcAyudaUso.setText("Ayuda sobre uso del sistema");
        opcAyudaUso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAyudaUsoActionPerformed(evt);
            }
        });

        menuAyuda.add(opcAyudaUso);

        opcAcercaDe.setText("Acerca de...");
        opcAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcAcercaDeActionPerformed(evt);
            }
        });

        menuAyuda.add(opcAcercaDe);

        menuBar.add(menuAyuda);

        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirse(evt);
            }
        });

        menuBar.add(menuSalir);

        setJMenuBar(menuBar);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-486)/2, (screenSize.height-75)/2, 486, 75);
    }//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSalirActionPerformed

    private void cerrarConexion(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cerrarConexion
        // TODO add your handling code here:
        objGestor.desconecta();
        System.exit(0);
    }//GEN-LAST:event_cerrarConexion

    private void opcAcercaDeActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcAcercaDeActionPerformed
    {//GEN-HEADEREND:event_opcAcercaDeActionPerformed
        // TODO add your handling code here:
        System.out.println("Acerca de...");
        new DlgMensajes(new javax.swing.JFrame(),"Acerca de...","Implantar una pantalla con el Acerca de con su CU y nombre ").show();
    }//GEN-LAST:event_opcAcercaDeActionPerformed

    private void opcAyudaUsoActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcAyudaUsoActionPerformed
    {//GEN-HEADEREND:event_opcAyudaUsoActionPerformed
        // TODO add your handling code here:
        System.out.println("Ayuda sobre el uso del Sistema...");
        new DlgMensajes(new javax.swing.JFrame(),"Ayuda del sistema","Implantar una pantalla con un texto de tres líneas en una jTextArea").show();
    }//GEN-LAST:event_opcAyudaUsoActionPerformed

    private void MenuInscripciones_onMouseClicked (java.awt.event.MouseEvent evt)//GEN-FIRST:event_MenuInscripciones_onMouseClicked
    {//GEN-HEADEREND:event_MenuInscripciones_onMouseClicked
        // TODO add your handling code here:
        //System.out.println("Inscripciones");
        //new DlgMensajes(new javax.swing.JFrame(),"Inscripciones","Implantar la funcionalidad de incribir alumno a grupo").show();
        FrmInscripciones frmInscripciones = new FrmInscripciones( objGestor);
        frmInscripciones.show();
    }//GEN-LAST:event_MenuInscripciones_onMouseClicked

    private void opcNivelesActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcNivelesActionPerformed
    {//GEN-HEADEREND:event_opcNivelesActionPerformed
        // TODO add your handling code here:
        System.out.println("Niveles");
        new DlgMensajes(new javax.swing.JFrame(),"Niveles","Implantar la pantalla de mantenimiento a Niveles").show();
    }//GEN-LAST:event_opcNivelesActionPerformed

    private void opcGruposActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcGruposActionPerformed
    {//GEN-HEADEREND:event_opcGruposActionPerformed
        // TODO add your handling code here:
        System.out.println("Grupos");
        new DlgMensajes(new javax.swing.JFrame(),"Grupos","Implantar la pantalla de mantenimiento a Grupos").show();
    }//GEN-LAST:event_opcGruposActionPerformed

    private void opcProfesoresActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcProfesoresActionPerformed
    {//GEN-HEADEREND:event_opcProfesoresActionPerformed
       System.out.println("Profesores");        // TODO add your handling code here:
       new DlgMensajes(new javax.swing.JFrame(),"Profesores","Implantar la pantalla de mantenimiento a Profesores").show();
    }//GEN-LAST:event_opcProfesoresActionPerformed

    private void opcAlumnosActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcAlumnosActionPerformed
    {//GEN-HEADEREND:event_opcAlumnosActionPerformed
        // TODO add your handling code here:
        System.out.println("Alumnos...");
        FrmAlumnos frmAlumnos = new FrmAlumnos(objGestor);
        frmAlumnos.show();
    }//GEN-LAST:event_opcAlumnosActionPerformed

    private void salirse (java.awt.event.MouseEvent evt)//GEN-FIRST:event_salirse
    {//GEN-HEADEREND:event_salirse
        // TODO add your handling code here:
        //System.out.println("Salir..."); 
        objGestor.desconecta();
        System.exit (0);      
    }//GEN-LAST:event_salirse
    
    private void opcBailesActionPerformed (java.awt.event.ActionEvent evt)//GEN-FIRST:event_opcBailesActionPerformed
    {
        System.out.println("Bailes");
        new DlgMensajes(new javax.swing.JFrame(),"Bailes","Implantar la pantalla de mantenimiento a Bailes").show();
        
}//GEN-LAST:event_opcBailesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main (String args[])
    {
        new FrmMenuPrincipal (null).show ();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuBasicos;
    private javax.swing.JMenu menuInscripciones;
    private javax.swing.JMenu menuSalir;
    private javax.swing.JMenuItem opcAcercaDe;
    private javax.swing.JMenuItem opcAlumnos;
    private javax.swing.JMenuItem opcAyudaUso;
    private javax.swing.JMenuItem opcBailes;
    private javax.swing.JMenuItem opcGrupos;
    private javax.swing.JMenuItem opcNiveles;
    private javax.swing.JMenuItem opcProfesores;
    // End of variables declaration//GEN-END:variables
    
}
